<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-N132HI4" failures="1" tests="13" name="Test" time="44.746" errors="0" timestamp="2021-11-03T13:23:29 IST">
  <testcase classname="BdynamicTestcases.TestNgAnnotation" name="testcase1" time="0.007"/>
  <testcase classname="BdynamicTestcases.TestNgAnnotation" name="testcase2" time="0.003"/>
  <testcase classname="AsataticTestcases.A" name="checkDigit" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [4] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [3]
at AsataticTestcases.A.checkDigit(A.java:8)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkDigit -->
  <testcase classname="AsataticTestcases.A" name="checkDigit1" time="0.002"/>
  <testcase classname="AsataticTestcases.B" name="logincheck" time="15.725"/>
  <testcase classname="AsataticTestcases.B" name="checkerrormsg" time="3.41"/>
  <testcase classname="AsataticTestcases.B" name="checkTitle" time="3.129"/>
  <testcase classname="AsataticTestcases.B" name="checkSubTitle" time="3.216"/>
  <testcase classname="AsataticTestcases.B" name="checkStartMsg" time="3.3"/>
  <testcase classname="BdynamicTestcases.DynamicTestCases" name="checkTitle" time="3.416"/>
  <testcase classname="BdynamicTestcases.DynamicTestCases" name="checkerrormsg" time="3.982"/>
  <testcase classname="BdynamicTestcases.DynamicTestCases" name="checklebal1" time="4.766"/>
  <testcase classname="BdynamicTestcases.DynamicTestCases" name="checklebal2" time="3.66"/>
</testsuite> <!-- Test -->
